### ISSUE TITLE
Unable to update translated attributes to empty value

### ISSUE THREAD

**Issue by uldza** [cubesystems/releaf#195]
Given there is translated attribute with some value saved. When changing value to blank and saving record - new attribute value isn't saved.

Looks like problem is in globalize_accessors gem - the setter returns, when blank value assigned.
https://github.com/globalize/globalize-accessors/blob/master/lib/globalize-accessors.rb#L39
If the line is commented out - update with blank value is successful.

It is possible to work around it in Releaf::BaseController before update calling each globalized attribute

```ryby
  @resource.globalize_attribute_names.each do |method|
    @resource.send method
  end
```

**Comment by miks** [comment]
Solved with globalize-accessors 0.2.1 release.
