### ISSUE TITLE
Calling eager_load! causes slowness in development

### ISSUE THREAD

**Issue by mkarklins** [cubesystems/releaf#207]
Troubling line:
https://github.com/cubesystems/releaf/blob/master/releaf-core/app/builders/releaf/builders.rb#L15

For my particular project, that line costs about 4 seconds:
`Benchmark.measure{ Rails.application.eager_load! } #=>`
`#<Benchmark::Tms:0x007feb85646e50 @label="", @real=4.564621 ...`

There should be a better way to load user-defined builders, without reloading all of `app` files.

**Comment by miks** [comment]
Fixed with #208
