### ISSUE TITLE
Node url and path methods

### ISSUE THREAD

**Issue by guntis** [cubesystems/releaf#265]
Currently node#url method returns a relative path to the node, e.g. "/en/products".

1) The current method name "url" is misleading and it should be renamed to "path" to match the convention of how the "_path" and "_url" suffixes are used in Rails route helpers.

2) A new method named "url" that would return the actual full URL, e.g. "http://example:3000/en/products", would also be helpful if it is possible to implement it reasonably. It gets tricky though, because accessing the hostname, port and protocol from inside the node model would be wrong, but maybe we can still think of some way to do it better. 

So far I have already encountered two real-world cases where I needed to get the full URL of a node instance, and in both cases I've had to manually prepend the protocol and host inside the controller or view.

**Comment by graudeejs** [comment]
Need to include Rails route helpers and 
```
def url
  root_url + node.path
end
```

That should be enough.

**Comment by miks** [comment]
Done with #268
