### ISSUE TITLE
Unify component naming

### ISSUE THREAD

**Issue by guntis** [cubesystems/releaf#271]
Currently component names are inconsistent. Some end with "Component" and some do not.

Releaf::Permissions has:

```
  def self.components
    [
      Releaf::Permissions::DeviseComponent,
      Releaf::Permissions::RolesComponent,
      Releaf::Permissions::UsersComponent,
      Releaf::Permissions::ProfileComponent
    ]
  end
```

Releaf::I18nDatabase has:

```
  def self.components
    [Releaf::I18nDatabase::HumanizeMissingTranslations]
  end
```

Releaf::Core has:

```
  def self.components
    [Releaf::Core::SettingsUIComponent]
  end
```

And releaf initializer by default has a mixture of both:

```
config.components = [
  Releaf::I18nDatabase, 
  Releaf::Permissions, 
  Releaf::Content, 
  Releaf::Core::SettingsUIComponent
]
```

I think the "Component" suffix is redundant and we should drop it from all component names. 

A component is just a module that may have a few optional methods that get executed automatically if defined (`initialize_component` and `draw_component_routes`), and that's it. A component does not even have to extend the `Releaf::Core::Component` module. Therefore, I think there is no real need to highlight that a module is a Releaf component by adding "Component" to its name.

**Comment by miks** [comment]
Fixed with #272
