### ISSUE TITLE
Javascript audit

### ISSUE THREAD

**Issue by miks** [cubesystems/releaf#279]

**Comment by skakri** [comment]
Quick suggestion: it'd be great if we could integrate jshint.

**Comment by miks** [comment]
Code Climate have eslint (https://github.com/codeclimate/codeclimate-eslint)

**Comment by skakri** [comment]
Even better. :+1:

**Comment by miks** [comment]
Here we go https://codeclimate.com/github/cubesystems/releaf/issues?category=&engine=eslint
