### ISSUE TITLE
Exclude localized html attributes from table builder

### ISSUE THREAD

**Issue by guntis** [cubesystems/releaf#294]
Currently, `Releaf::ResourceTableFields#table_excluded_attributes` only returns base column names ending with _html as exclusions. Localized attributes ending with _html should also be excluded.

**Comment by guntis** [comment]
File fields ending with _uid should also be excluded from the tables by default.

**Comment by graudeejs** [comment]
Preferably when they are checked that they are in fact dragonfly accessor fields.

**Comment by miks** [comment]
I started to think about resolving and caching these properties while environments other than test/dev.
Like in this case, we are resolving whether class have dragonfly accessories for form builder and then resolved properties can be used also for table view.

**Comment by miks** [comment]
Fixed with #296
