### ISSUE TITLE
Improve consistency of the default text search behaviour

### ISSUE THREAD

**Issue by guntis** [cubesystems/releaf#298]
Until now I was under the impression that the text search feature is using all text/string attributes of the model by default, unless searchable fields get explicitly specified in the controller. Turns out, it only looks for a predefined list of possible magic attributes like "name", "title", "email", "username", "first_name", "last_name" etc.

This is quite confusing and leads to inconsistencies. If I create a blank controller for a model that has a "name" attribute, the search field is immediately there and working. If I add a blank controller for, say, a FaqItem model that has a "question" attribute instead of "name", then the table shows the column by default, but there is no search form and I have to start investigating why.

I see two options:

1) Make it consistent and predictable. Search in all values that are displayed in the index view. 

This is how a correctly implemented search should work - search **only** in data that is immediately visible to the user (there is no point in searching in hidden attributes by default), and search in **all** data that is visible. This means also searching in all displayed localized fields of the model (but only in the locale that is currently being displayed to the user!), and maybe even in any association columns rendered in the table, if possible.

The list of displayed columns is defined in the table builder. It seems dirty to try accessing the builder from the searcher code, but maybe we can think of a reasonable way to do it. If implemented, this would remove almost any need to ever define searchable fields manually, unless some heavy customization is needed.

2) Remove it. If the above option cannot be reasonably implemented, perhaps we should disable text search by default and require the developer to explicitly define the searchable_fields array in the controller. 

This way at least the developer would be aware that he is adding a search, even though the user would still have no way of guessing which attributes will be searched.

The downside to this is that the search feature would no longer ever work immediately out of the box as a nice built-in UX extra, and I am sure that developers will almost never bother to define the searchable fields on their own, unless explicitly asked, so the search will be used quite rarely - probably only when someone already complains about having a hard time working with many records (much too late).

Any other options?

**Comment by graudeejs** [comment]
Well you can't search by stuff that user sees, you can only search by sql table columns.
The reasons you can't search like that is simple: Imagine you have person class that holds first_name and last_name, but in index you see name, which is composite of both attributes. This is the most simple example.

I however agree to you point that it's hard to know which field will be searchable.

For this we could search string fields. and string fields of associated translations in current locale.

But what happens when you want to find record in different locale. I mean you know the value in French and want to find that record? Searching by current locale will disable this feature.

Also consider this: your public page is in LV and RU locales, but your admin is in EN. How will you find records?

Taking all that into account I'd vote for string search in all locales.

**Comment by guntis** [comment]
Searching various computed fields is an edge case that could be left to the developer to implement, if needed. It's true that we cannot automatically search in non-attribute columns, but I'm talking more about reasonable default behaviour for standard everyday cases. 

Also, simple composite fields may not be a problem. A correctly implemented text search should match across all searchable columns anyway, without requiring the full search string to be inside a single column. I've implemented such search queries before and the SQL is not at all complicated once the list of columns is known, which is the hard problem here.

As for searching in non-visible locales, I'd say that it is also more of an exception and not the usual case. There may be cases when it could be relevant, but I think that having it on by default would again lead to confusion. I enter "asd" in the search field, I see that records are filtered and I now have 10 instead of 100 records displayed, yet none of them have "asd" anywhere in the table, because they have been matched in other languages. How would I know which one is the one I'm looking for? 

Your second example with admin being in EN and the resources having only LV and RU locales is an even weirder scenario that would require other solutions in general, since having the localized attribute in the table would make no sense then - the column would always be empty anyway. In that case, I would probably add :title_lv and :title_ru as separate visible columns instead of just showing :title in the current locale.

**Comment by graudeejs** [comment]
I provided bad example - searcher will for for this case.

As for searching in different locales - it's not that uncommon scenario. And no Adding title_lv and title_ru is not a sollution. In fact, if you do that then searcher would still search in lv and ru as these would be strings and searcher will search all strings of model (it has no way of knowing that title_ru is title for Russian and title_lv for Latvian).
