### ISSUE TITLE
releaf-3c0aab0a3faa/releaf-permissions/lib/releaf/permissions/default_controller_resolver.rb:5:in `configure_component': undefined method `root' for #<Releaf::Configuration:0x007fb652447b30> (NoMethodError)

### ISSUE THREAD

**Issue by liepa** [cubesystems/releaf#305]

**Comment by miks** [comment]
Can you post your `config/initializers/releaf.rb` config.components content?

**Comment by liepa** [comment]
config.components = [Releaf::I18nDatabase, Releaf::Permissions, Releaf::Content, Releaf::Core::SettingsUIComponent]

**Comment by miks** [comment]
Thats why we have https://github.com/cubesystems/releaf/blob/master/CHANGELOG.md
