### ISSUE TITLE
postgresql random fails on Travis CI

### ISSUE THREAD

**Issue by miks** [cubesystems/releaf#306]
@graudeejs can you, please, investigate this?

ex. https://travis-ci.org/cubesystems/releaf/jobs/114179800
Errors are same every failed build.

**Comment by graudeejs** [comment]
I'll try to fix that on weekend, but I can't promise.
Could you assign this issue to me?

**Comment by miks** [comment]
It's not top priority at all, but it will be nice to get posgtresql on Travis CI working. This week or next, no big deal.

**Comment by graudeejs** [comment]
I'm having difficulties reproducing this issue
