### ISSUE TITLE
localization update & caching issue

### ISSUE THREAD

**Issue by graudeejs** [cubesystems/releaf#312]
When you translate some key via admin menu on production and reload page that uses these localizations sometimes you can see default localization (un-localized version) of text.

Since this happens on production, it's related to multiple unicorn workers & cache.

**Comment by miks** [comment]
If there is no way how to reproduce it, there is no way how to fix it.

**Comment by miks** [comment]
I think its related with older rails-settings-cached versions. We had these issues and solved with latest rails-settings-cached version (v0.6.4 or newer)
