### ISSUE TITLE
Add default_settings.yml

### ISSUE THREAD

**Issue by guntis** [cubesystems/releaf#319]
After the recent settings gem update, our initializer code `Releaf::Settings.register` stopped working in tests. It registers the settings fine when the application is actually running, but the settings are not stored when running in test env.

This is remedied by using `stub_settings` in tests that need access to some settings. Yet there is no way of testing that the needed settings have actually been registered in the application and that all of them have working default values.

We could introduce a YAML file for settings and their defaults/types/descriptions, so that there is no need to call `Releaf::Settings.register` from the initializer. 

In tests, the `stub_settings` helper could check against the YAML file and throw an error in case a setting is being stubbed which is either not defined or does not have a default value in the YAML file.

**Comment by miks** [comment]
I will close as it is possible to test default settings with code like this:
```
expect(Releaf::Settings.registry[setting_key]).to_not be_nil
```
