### ISSUE TITLE
Sanitize index_url

### ISSUE THREAD

**Issue by guntis** [cubesystems/releaf#322]
Currently, if the `index_url` is passed in query string, it is used for links and redirects exactly as given, allowing to create a URL which can send the administrator out of the administration system to a malicious website. 

To avoid this, `current_url` and `index_url` methods should strip out the protocol and host parts of their values, so that the URLs are always relative to the current site.

**Comment by guntis** [comment]
For consistency, these methods should probably also be renamed to `current_path` and `index_path` when this change is implemented.

**Comment by miks** [comment]
Done.
