### ISSUE TITLE
Fix inconsistencies between empty countable and uncountable translations with default values

### ISSUE THREAD

**Issue by guntis** [cubesystems/releaf#327]
Everything works correctly when translation keys do not yet exist and are being created for the first time.

```
2.3.1 :039 > I18n.t('foo foo', default: 'foo foo')
 => "foo foo"
2.3.1 :040 > I18n.t('%{count} bar bar', count: 1, create_plurals: true, default: '%{count} bar bar')
 => "1 bar bar"
```

After this, the created translation keys in `releaf_i18n_entries` are:

```
"foo foo"
"%{count} bar bar.one"
"%{count} bar bar.few"
"%{count} bar bar.many"
"%{count} bar bar.zero"
"%{count} bar bar.other"
```

(The exact list may vary depending on locales used in the system).

There are no new records in `releaf_i18n_entry_translations` at this point.

A user goes to the translations index view in releaf, opens these new translations for editing and presses "Save" without filling in any texts.

Empty records are created in the `releaf_i18n_entry_translations` for all of these keys in each available locale.

After this, the behaviour of the same code starts to differ.

```
2.3.1 :069 > I18n.t('foo foo', default: 'foo foo')
 => "foo foo"
2.3.1 :089 > I18n.t('%{count} bar bar', count: 1, create_plurals: true, default: '%{count} bar bar')
 => nil
```

The countable translations no longer return the default value. 

Both lines should always work the same way and return the default value if the translation is missing or empty.

**Comment by miks** [comment]
Fixed with 2015c33
